---
title: "trial"
author: "Ong Zhi Rong Jordan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
packages = c('sf', 'tmap', 'tidyverse', 
             'lubridate', 'clock', 
             'sftime', 'rmarkdown', "binr","ggplot2","ggpubr")
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}

```

``` {r}

Region <- st_read('data/buildings.shp')
buildings <- read_sf("data/Buildings.csv", 
                     options = "GEOM_POSSIBLE_NAMES=location")
participants <- read_rds("data/hw2_participants.rds")
apartments_1 <- readRDS("data/apartments_new.rds")
participants_details <- readRDS("Participant_Details.rds")

```


``` {r}
apartments_1 <- apartments_1 %>%
  select (participantId, buildingId) %>%
  rename('Participant_ID' = 'participantId')

participants_details <- participants_details %>%
  left_join(apartments_1, by = "Participant_ID")

```

``` {r}

building_plot <- participants_details %>%
  group_by(buildingId,Region,Joviality_Level) %>%
  summarise(StayCount = n()) %>%
  filter (Joviality_Level == "Happy_Participant")

building_plot$buildingId <- as.character(building_plot$buildingId)


```

``` {r}

building_new <- buildings %>%
  left_join(building_plot, by= 'buildingId')

st_as_sf(building_new)

tmap_mode("view")
tm_shape(building_new)+
  tm_polygons(col = "StayCount",
              size = 1,
              title = "Building Type",
              border.col = "black",
              border.lwd = 1) +
  tm_layout(main.title= 'Building Type in Engagement, Ohio', 
            main.title.position = c('left'),
            main.title.size = 1.3, legend.outside = TRUE,)
```


``` {r}

participants_1 <- participants %>%
  select (participantId, Apartmentvisits)

Region_1 <- Region %>%
  select (units, region,-geometry)

```

``` {r}

a <- st_set_geometry(Region_1,NULL)

apartment_long <- a %>% tidyr::separate_rows(units, convert = TRUE)
participants_full <- participants_1 %>% left_join(apartment_long, by = c("Apartmentvisits" = "units"))

```

``` {r}

participants_full <- participants_full %>%
  rename('Participant_ID' = 'participantId')

Part_nodes <- Part_nodes %>%
  left_join(participants_full, by = "Participant_ID")
```

``` {r}
high_income <- quantile(Part_nodes$Income,0.8, na.rm = TRUE)
low_income <- quantile(Part_nodes$Income,0.2, na.rm = TRUE)

high_joy <- quantile(Part_nodes$Joviality,0.8, na.rm = TRUE)
low_joy <- quantile(Part_nodes$Joviality,0.2, na.rm = TRUE)

Part_nodes_full <- Part_nodes %>%
  mutate (
    Income_Level = case_when(
      Income >= high_income ~ "High_Income_Earner",
      Income <= low_income ~ "Low_Income_Earner",
      is.na(Income) ~ "NA",
      TRUE ~ "Medium_Income_Earner"
    )
  ) %>%
  mutate (
    Joviality_Level = case_when(
      Joviality >= high_joy ~ "Happy_Participant",
      Joviality <= low_joy ~ "Dull_Participant",
      TRUE ~ "Average_Participant"
    )
  ) %>%
  rename("Region" = "region") %>%
  select(-Joviality,-Income,-Apartmentvisits,-Expenses)

```

```{r}
saveRDS(Part_nodes_full, "Participant_Details.rds")

```


``` {r}
total_month_data$time <- factor(total_month_data$time,levels = c("Mar 22", "Apr 22", "May 22", "Jun 22", "Jul 22", "Aug 22", "Sep 22", "Oct 22", "Nov 22", "Dec 22", "Jan 23", "Feb 23", "Mar 23", "Apr 23", "May 23"))

saveRDS(total_month_data,"total_month_data_new.rds")
```


```{r}

# Create dataset
data=data.frame(
  individual=paste( "Mister ", seq(1,60), sep=""),
  group=c( rep('A', 10), rep('B', 30), rep('C', 14), rep('D', 6)) ,
  value1=sample( seq(10,100), 60, replace=T),
  value2=sample( seq(10,100), 60, replace=T),
  value3=sample( seq(10,100), 60, replace=T)
)
 
# Transform data in a tidy format (long format)
data = data %>% gather(key = "observation", value="value", -c(1,2)) 
 
# Set a number of 'empty bar' to add at the end of each group
empty_bar=2
nObsType=nlevels(as.factor(data$observation))
to_add = data.frame( matrix(NA, empty_bar*nlevels(data$group)*nObsType, ncol(data)) )
colnames(to_add) = colnames(data)
to_add$group=rep(levels(data$group), each=empty_bar*nObsType )
data=rbind(data, to_add)
data=data %>% arrange(group, individual)
data$id=rep( seq(1, nrow(data)/nObsType) , each=nObsType)
 
# Get the name and the y position of each label
label_data= data %>% group_by(id, individual) %>% summarize(tot=sum(value))
number_of_bar=nrow(label_data)
angle= 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust<-ifelse( angle < -90, 1, 0)
label_data$angle<-ifelse(angle < -90, angle+180, angle)
 
# prepare a data frame for base lines
base_data=data %>% 
  group_by(group) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))
 
# prepare a data frame for grid (scales)
grid_data = base_data
grid_data$end = grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start = grid_data$start - 1
grid_data=grid_data[-1,]
 
# Make the plot
p = ggplot(data) +      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=value, fill=observation), stat="identity", alpha=0.5) +
  scale_fill_viridis(discrete=TRUE) +
  
  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 0, xend = start, yend = 0), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 50, xend = start, yend = 50), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 100, xend = start, yend = 100), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 150, xend = start, yend = 150), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 200, xend = start, yend = 200), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
  # Add text showing the value of each 100/75/50/25 lines
  annotate("text", x = rep(max(data$id),5), y = c(0, 50, 100, 150, 200), label = c("0", "50", "100", "150", "200") , color="grey", size=2 , angle=0, fontface="bold", hjust=1) +
  
  ylim(-150,max(label_data$tot, na.rm=T)) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  coord_polar() +
  
  # Add labels on top of each bar
  geom_text(data=label_data, aes(x=id, y=tot+10, label=individual, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=1, angle= label_data$angle, inherit.aes = FALSE ) +
  
  # Add base line information
  geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE )  +
  geom_text(data=base_data, aes(x = title, y = -18, label=group), hjust=c(1,1,0,0), colour = "black", alpha=0.8, size=4, fontface="bold", inherit.aes = FALSE)

p

```

``` {r}

Social_edge_selected_workdays_new <- Social_edge_selected_workdays %>%
  group_by(weeknum,month,workday) %>%
  summarise(value = n())

Social_edge_selected_workdays_new$weeknum <- as.character(Social_edge_selected_workdays_new$weeknum)
Social_edge_selected_workdays_new$month <- as.character(Social_edge_selected_workdays_new$month)

Social_edge_selected_workdays_new_df <- as.data.frame(Social_edge_selected_workdays_new)

levels(Social_edge_selected_workdays_new_df$month) <- c("Jan", "Feb", "Mar", "Apr", "May","Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")


```

``` {r}

# Set a number of 'empty bar' to add at the end of each group
empty_bar=2

nObsType=nlevels(as.factor(Social_edge_selected_workdays_new_df$workday))

to_add <- data.frame( matrix(NA, empty_bar*nlevels(as.factor (Social_edge_selected_workdays_new_df$month))*nObsType, ncol(Social_edge_selected_workdays_new_df)) )

colnames(to_add) <-  colnames(Social_edge_selected_workdays_new_df)
to_add$month <- rep(levels(as.factor(Social_edge_selected_workdays_new_df$month)), each=empty_bar*nObsType)
Social_edge_selected_workdays_new_df <- rbind(Social_edge_selected_workdays_new_df, to_add)
Social_edge_selected_workdays_new_df <- Social_edge_selected_workdays_new_df %>% arrange(month, weeknum)
Social_edge_selected_workdays_new_df$id=rep( seq(1, nrow(Social_edge_selected_workdays_new_df)/nObsType) , each=nObsType)

# Get the name and the y position of each label
label_data= Social_edge_selected_workdays_new_df %>% group_by(id, weeknum) %>% summarize(tot=sum(value))
number_of_bar=nrow(label_data)
angle= 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust<-ifelse(angle < -90, 1, 0)
label_data$angle<-ifelse(angle < -90, angle+180, angle)

# prepare a data frame for base lines
base_data=Social_edge_selected_workdays_new_df %>%
  group_by(month) %>%
  summarize(start=min(id), end=max(id) - empty_bar) %>%
  rowwise() %>%
  mutate(title=mean(c(start, end)))

# prepare a data frame for grid (scales)
grid_data = base_data
grid_data$end = grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start = grid_data$start - 1
grid_data=grid_data[-1,]

```

``` {r}

p = ggplot(social_circular_barplot) +      
  
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=value, fill=workday), stat="identity", alpha=0.5) +
  scale_fill_tron()+
  
  # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 0, xend = start, yend = 0), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 50000, xend = start, yend = 50000), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 100000, xend = start, yend = 100000), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 150000, xend = start, yend = 150000), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 200000, xend = start, yend = 200000), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  
  # Add text showing the value of each 100/75/50/25 lines
  annotate("text", x = rep(max(social_circular_barplot$id),5), y = c(0, 50000, 100000, 150000, 200000), label = c("0", "50000", "100000", "150000", "200000") , color="grey", size=2 , angle=0, fontface="bold", hjust=0.8) +
  
  ylim(-200000,max(label_data$tot + 1000, na.rm=T)) +
  labs(title = "Social Interaction of Participants by Month and Week", caption = "From Mar 22 - Feb 23", fill = "Workday Type") +
  theme_minimal() +
  theme(
    legend.position="right",
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid = element_blank()
  ) +
  coord_polar(start = 0) +
  # Add labels on top of each bar
  geom_text(data=label_data, aes(x=id, y=tot+1000, label=weeknum, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=3, angle= label_data$angle, inherit.aes = FALSE ) +
  # Add base line information
  geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size= 0.4 , inherit.aes = FALSE ) +
  geom_text(data=base_data, aes(x = title, y = -25000, label=as.factor(month)), hjust=c(1,1,1,1,1,1,0,0,0,0,0,0), colour = "black", alpha=0.7, size=3, fontface="bold", inherit.aes = FALSE)
p

```

``` {r}

saveRDS(grid_data,"grid_data.rds")
saveRDS(label_data,"label_data.rds")
saveRDS(base_data,"base_data.rds")
saveRDS(Social_edge_selected_workdays_new_df,"social_circular_barplot.rds")


```


``` {r}

p <- ggplot (Social_edge_selected_workdays_new_df, aes(x = as.factor(id), y = value, fill = workday)) +
  scale_fill_tron()+
  geom_bar (stat = "identity", position = "stack", alpha = 0.5) +
  ylim(-180000,200000) +
  
  theme_minimal() +
  theme (
    axis.text =  element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-2,4), "cm")
  ) +
  coord_polar(start = 0) +
  
  geom_text (data = label_data,
             aes(x = id, y = tot + 10,
                 label = weeknum,
                 hjust = hjust),
             color = "black",
             fontface = "bold",
             alpha = 0.6,
             size = 2.5,
             angle = label_data$angle,
             inherit.aes = FALSE)

p

```