---
title: "Question 1"
description: |
  Vast Challenge 2022-Question 1
author:
  - name: Bomin Kim 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Reading packages

```{r}
packages = c('sf', 'tmap', 'tidyverse', 
             'lubridate', 'clock', 
             'sftime', 'rmarkdown', "binr","ggplot2","ggpubr")
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

```{r}

buildings <- read_sf("data/Buildings.csv", 
                     options = "GEOM_POSSIBLE_NAMES=location")
participants <- read_rds("data/hw2_participants.rds")
apartments_new <- readRDS("data/apartments_new.rds")
buildingsshx<-st_read("data/buildings.shx")
```


```{r}
#
buildings<-st_join(buildings,buildingsshx%>%
                      select(region)%>%
                mutate(region=as.character(region)),by=c("buildingId"="bldngId"))

apartments_withid<-merge(apartments_new,participants[,c("participantId","agegroup","wage","joviality","haveKids")],by="participantId",all.x=TRUE)

apartments_withid<-left_join(apartments_withid,buildings%>%
                               select(buildingId,region)%>%
                               mutate(region=as.character(region)),by=c("buildingId"="buildingId"))

apartments_withid<-as.data.frame(apartments_withid)
#apartments_withid is the dataframe for plotting graphs

buildings_withid<-left_join(buildings,
                              apartments_withid%>%
                                mutate(buildingId=as.character(buildingId)),
                              by=c("buildingId"="buildingId"))
#buildings_withid is the sf object for tmap plotting
```


